RED: test two: Pushes a single object on the Stack and verifies that IsEmpty is false
  1) Stack Pushes a single object on the Stack and verifies that IsEmpty is false
     Failure/Error: stack.Push("first element")
     NoMethodError:
       undefined method `Push' for #<Stack:0x007fb9f9c42e70 @is_empty=true>
     # ./spec/stack_spec.rb:12:in `block (2 levels) in <top (required)>'