RED: test three: Push a single object, Pop the object, and verify that IsEmpty is true.
  1) Stack Push a single object, Pop the object, and verify that IsEmpty is true.
     Failure/Error: stack.Pop
     NoMethodError:
       undefined method `Pop' for #<Stack:0x00000102872708 @is_empty=false>
     # ./spec/stack_spec.rb:17:in `block (2 levels) in <top (required)>'