RED: test seven: Push a single object and then call Top. Verify that IsEmpty is false.
  1) Stack Push a single object and then call Top. Verify that IsEmpty is false.
     Failure/Error: stack.Top
     NoMethodError:
       undefined method `Top' for #<Stack:0x000001018b0e28 @elements=["42"]>
     # ./spec/stack_spec.rb:50:in `block (2 levels) in <top (required)>'