RED: test one: creates a Stack and verifies that IsEmpty is true.
  1) Stack creates a Stack and verifies that IsEmpty is true.
     Failure/Error: expect(stack.IsEmpty).to be(true)
     NoMethodError:
       undefined method `IsEmpty' for #<Stack:0x000001018a86d8>
     # ./spec/stack_spec.rb:7:in `block (2 levels) in <top (required)>'